from pathlib import Path
import re, json, shutil, difflib, hashlib, html
ROOT=Path(__file__).resolve().parents[4]
SRC=ROOT/'新方向手稿'/'overleaf'
OUT=ROOT/'新方向手稿'/'language_edit_20260913'
PKG=OUT/'overleaf'
PKG.mkdir(parents=True,exist_ok=True)
for name in ['main.tex','supplement.tex','references.bib','interact.cls','natbib.sty','tfcad.bst','subfigure.sty','rotating.sty','epsfig.sty']:
    shutil.copy2(SRC/name,PKG/name)
for name in ['figures','reproducibility']:
    shutil.copytree(SRC/name,PKG/name,dirs_exist_ok=True)
original={n:(SRC/n).read_text(encoding='utf-8') for n in ['main.tex','supplement.tex']}
texts=original.copy()
edits=[]
def para(file,start,new,purpose):
    text=texts[file]
    if start=='Low-altitude capacity alone':
        start='\\begin{abstract}'
        new='\\begin{abstract}\n'+new.strip()+'\n\\end{abstract}'
    matches=[p for p in text.split('\n\n') if p.lstrip('\n').startswith(start)]
    assert len(matches)==1,(file,start,len(matches))
    old=matches[0]
    new=new.strip()
    assert new!=old,start
    texts[file]=text.replace(old,new,1)
    edits.append(dict(file=file,anchor=start,purpose=purpose,original=old,edited=new))
def m(start,new,purpose): para('main.tex',start,new,purpose)
def s(start,new,purpose): para('supplement.tex',start,new,purpose)

m('Low-altitude capacity alone',r'''Available aircraft do not by themselves keep disrupted transport services on time. An intervention must provide useful service before the remaining deadline margin runs out. We propose a Ground--Low-Altitude Mobility Manager in which a candidate generator converts joint ground--air observations into a shared executable candidate interface. Replaceable supervisory policies use common feasibility, completion-time and incumbent-service facts to select an intervention. The executor checks and applies the proposal, while local contingencies operate independently. Four SUMO--BlueSky experiments across three contrasting transport settings examine selective air support, air failures, compound disturbances and observation--execution timing. At the meshed urban site, the fixed-objective heuristic and LLM-candidate policy both reduce emergency deadline violations from 33.33\% to 16.67\%, but leave 0.058 and 0.133 damaged incumbent services per run, respectively. Explicit candidate-information support changes choices when faster air service would interrupt an incumbent service. Every affected coordinated run restores a path after a single air failure, yet 39.06\% of all LLM-policy runs at that site remain late. Delayed observation uses up the remaining margin. Waiting for execution can also change the intervention when a newer command replaces the pending one. The study provides an executable architecture for comparing service-management policies. It shows how surviving alternatives, incumbent-service costs and intervention timing govern realized resilience. Operators therefore need to secure timely, useful reconfiguration: available air capacity or a restored path alone does not establish service recovery.''','摘要：先交代服务问题，再分清生成、选择、执行及独立应急；保留全部结果与边界。')
m('Restoring network connectivity',r'''Restoring network connectivity does not necessarily restore transport service. An urgent mission may still have a road route but no longer have enough time to meet its deadline. A useful response must preserve on-time completion within the remaining service margin. Reassigning a vehicle can rescue that mission while interrupting another service. Disruption management must therefore consider both deadline compliance and how service losses are distributed, consistent with performance-based transport resilience assessment. \citep{ref1}''','引言：用任务、时间和车辆改派说明交通问题。')
m('Low-altitude resources offer',r'''Low-altitude resources offer a way around disrupted ground links. Their value depends on where they are, which tasks they can serve and whether they are already occupied. Using a faster aircraft may require preempting an incumbent service even when continued ground transport would meet the deadline. Communication loss, degraded navigation or an unavailable landing site can also remove the air alternative after dispatch. The management problem is to select and execute useful cross-modal interventions as resources and deadlines change.''','引言：将资源价值和抢占后果写成具体条件。')
m('Multimodal recovery and',r'''Multimodal recovery and Resilience as a Service coordinate heterogeneous replacement services, while dynamic fleet management and truck--drone routing address changing assignments and synchronization. \citep{ref4,ref19,ref20,ref21,ref22} Constrained-execution architectures distinguish a proposed action from permission to apply it. \citep{ref8} We bring these ideas together for supervisory service reconfiguration, using a failure-prone air layer to support disrupted ground services. A common interface describes feasible interventions and their consequences. It allows us to compare selection policies under controlled conditions and trace why a feasible replacement can still arrive too late.''','引言：明确已有工作与本文研究问题之间的联系。')
m('We propose the \\textbf',r'''We propose the \textbf{Ground--Low-Altitude Mobility Manager} (hereafter, the Manager). It connects joint state observations, deterministic candidate generation, replaceable supervisory selection and common execution checks. The \textbf{shared executable candidate interface} reports resource compatibility, legality, estimated completion and the incumbent service each option would displace. The supervisor selects one intervention. The executor normalizes and validates the proposal, then issues it or queues it for revalidation. Local contingencies operate independently. Here, global state means the joint state of one modeled study area. Ground service uses a SUMO corridor ETA timer; air transport evolves in BlueSky.''','定义：保留完整名称首次定义，锁定 Manager 简称和各模块职责。')
m('We make three contributions.',r'''We make three contributions. First, we develop a supervisory architecture for ground--air service reconfiguration that specifies how observations, selection and execution interact. Second, we provide the shared candidate interface and compare ground-only, air-first, fixed-objective heuristic and LLM-candidate policies. Third, we quantify how surviving alternatives, service trade-offs and observation--execution timing affect transport outcomes. Selective air support can reduce missed deadlines while displacing incumbent services. A restored path can still finish late, and delayed execution can allow a new command to replace the selected action. Figure~\ref{fig:fig01} links these findings to E1 selective support, E2 single air failure, E3 compound disturbance and E4 timing and input burden.''','贡献：用操作和可观察结果替代抽象机制堆叠，维持原段功能。')
m('Jaber et al. formulate',r'''Jaber et al. formulate Resilience as a Service through resource allocation among buses, taxis and automated vans that can bridge disrupted rail services. \citep{ref20} Their work provides a close precedent for coordinating heterogeneous replacement services. Our setting adds a failure-prone air layer. We compare interchangeable supervisory policies through the shared candidate interface and examine how their executed interventions affect service.''','相关工作：合并相邻两句重复的接口与可替换策略说明。')
m('At the network level,',r'''At the network level, Wollenstein-Betech et al. jointly optimize intermodal vehicle routing and rebalancing while accounting for congestion generated by vehicle flows. \citep{ref22} Our model selects an intervention for an actionable service and represents ground transport through a shared corridor travel-time proxy. It does not optimize network-wide routing flows or truck--drone launch-and-retrieval tours. We compare how policies select, preserve or replace services as modeled feasibility changes. B2 ranks candidates one step at a time using an explicit preference between faster completion and preserving incumbent service.''','相关工作：说清决策粒度与 B2 的具体选择，不扩大研究范围。')
m('Our candidate generator exposes',r'''The candidate generator reports common feasibility, completion-time and incumbent-service facts before the supervisor selects an action. The executor then checks the chosen action against the current state. Policies can therefore express different preferences while using the same rules for deriving information and checking execution. This separation also lets us trace what happens between a feasible proposal and the intervention that executes.''','相关工作：明确 generator、supervisor、executor 和时间间隔。')
m('Our comparison asks how policies',r'''We ask how policies use the common service-management contract and when their executed interventions protect service. The B4a--B4b comparison separately tests explicit candidate-information support within the same LLM implementation. The ablation removes derived per-candidate facts as well as their presentation, so it tests information support rather than table formatting alone.''','相关工作：保留消融解释范围，减少自我说明。')
m('A disruption can alter',r'''A disruption can change ground travel time, interrupt a selected air chain, remove an aircraft from supervisory control or eliminate a landing option. The same external event can affect policies differently because their earlier assignments determine which missions are exposed. Cross-modal reconfiguration changes a task's resource or transport mode, or changes how an existing operation continues. It can improve an emergency's outcome while interrupting or otherwise changing the state of an incumbent service.''','问题定义：解释既往决策如何改变故障暴露和服务后果。')
m('The interface contains no',r'''The interface contains no B2 objective score, optimizer selection or manager-specific recommended action. It does, however, reflect shared modeling choices: priority constraints, travel-time approximations and the organization of multi-mission records. Here, manager-agnostic means that policies use the same generation rules and facts at a given state. It does not mean that the representation is free of operational assumptions. After policies take different actions, their states and candidate sets can also differ.''','定义：保留 manager-agnostic 的严格边界，拆开概念密集句。')
m('A proposal replaced by',r'''A newer command can supersede a pending proposal; the executor rejects a proposal that fails the current checks. Neither supersession nor rejection means that transport has been completed. The subsequent state follows''','执行定义：区分替换、拒绝和运输完成。')
m('A nonempty feasible set',r'''A feasible candidate set may contain no alternative predicted to finish on time. Even a nonnegative estimated margin does not guarantee on-time completion: later failures, queue changes or estimation error can change the outcome. Equation (8) links candidate facts to the decision regimes analyzed in Figure~\ref{fig:fig04}.''','时间可行性：简化集合套叠的文字解释，公式保持原样。')
m('The framework couples SUMO',r'''The simulation environment couples SUMO for road traffic with BlueSky for aircraft movement. \citep{ref12}, \citep{ref13} A master orchestrator advances both layers in 1 s steps, maintains the service registry, and applies events and accepted interventions. Figure~\ref{fig:fig01}(b) places the replaceable policy within this sequence. Local aircraft contingencies operate independently of supervisory inference.''','方法：以 simulation environment 和 orchestrator 代替泛指 framework。')
m('The snapshot combines road',r'''The snapshot combines road estimates and closures with aircraft assignments, endurance, commandability, landing-site conditions, and mission priorities and deadlines. Ground candidates use the shared D1--H1 corridor ETA, including for eligible missions in the multi-mission interface. When ground fallback executes, the executor queries the current SUMO corridor estimate and schedules completion using the rounded duration. A mission timer records completion; the model does not dispatch and track a separate road vehicle for each fallback mission.''','方法：明确 ground fallback 查询和计时的主体，保留地面模型边界。')
m('Coupling occurs through task',r'''The simulators are coupled through task status and resource assignment. A new air assignment routes the aircraft from its current position through the mission origin to the destination. For an interrupted mission, the candidate route passes through the contingency site V3 before reaching the destination. Preemption detaches the incumbent mission and changes the aircraft's assignment. Local return or diversion continues separately. Replacement dispatch does not require verification that the original payload has arrived at V3. The registry does not model payload custody, unloading, reloading or re-shipment. Ground fallback changes the mission's mode and schedules completion from the live corridor ETA; it uses the proposal ETA only if the live query is unavailable. These rules represent service replacement. Supplementary Section S4 separately examines physical transfer time through an offline sensitivity analysis of the remaining margin.''','方法：按新派遣、故障后替代、独立应急、地面接替顺序解释现有语义。')
m('The candidate generator maps',r'''The candidate generator computes candidate facts from the observed global state. The shared executable candidate interface defines the fields and action semantics available to the supervisor. It makes air and ground alternatives comparable without recommending a selection. All candidates use the same convention for estimated remaining completion duration. Air estimates combine modeled route geometry, role-specific cruise speeds and dispatch overhead; ground candidates use the common fallback estimate. The interface also reports estimated absolute completion time, remaining deadline margin and whether preemption would interrupt an incumbent service. The supervisor uses these estimates to choose an intervention. At execution, the executor refreshes operational quantities from the environment and applies deterministic checks against the modeled constraints.''','方法：区分候选生成、接口、选择与执行时更新。')
m('The generator does not run',r'''The generator does not run B2 or receive its preference weights. B1 and B2 select from the shared table, while B4b receives that table in its prompt. The interruption indicator records whether reassignment would displace an existing service. It is neither a learned welfare estimate nor a cost weighted by B2.''','方法：解释中断标记的含义及不代表什么。')
m('\\noindent\\textbf{A decision',r'''\noindent\textbf{Faster emergency transport at the cost of an incumbent service.} At Site A, high disruption and high medical workload leave a ground route that meets the deadline and one faster air option that requires preemption. At 300 s in seed 20240601, the HIGH-priority emergency is due at 600 s. The logged candidates are:''','场景：以实际任务速度和既有服务中断说明 service-preservation pressure。')
m('B2 selected ground and',r'''B2 selected ground and completed the emergency mission in 229 s. B4b reassigned M-UAV-02 and completed it in 212 s, leaving one damaged incumbent service. B1 also selects the legal air option under its air-first rule. All three policies use the same candidate facts. Air offers an estimated 15.794 s speed advantage, but both alternatives meet the emergency deadline and only air displaces an incumbent. The fastest option therefore has the larger system service cost in this example. Candidate ETA remains an estimate; realized air completion also depends on simulator motion and the arrival radius.''','场景：保留所有数值、比较方向和 ETA 限定，分开行为与解释。')
m('B1\'s air-first ordering',r'''B1 minimizes ETA among legal air candidates. It considers ground only when no legal air option remains, so it does not minimize travel time across both modes. B2 selects the actionable mission under the priority rule, then ranks its legal air and ground candidates using''','策略差异：分别交代 B1 的模式优先与 B2 的跨模式排名。')
m('B4b uses the common prompt',r'''B4b uses the common prompt template with temperature 0, JSON output mode and an output-token budget of 8192. The recorded backend identifier, \nolinkurl{corp-ai/openai/deepseek-v4-pro}, identifies the configured service; the underlying release is unverified. B4a uses the same snapshot, prompt rules and checker but omits the candidate section. It therefore lacks per-resource air ETA, explicit legal/rejection flags, deadline consequences and the mapped consequence for the preempted service. Raw assignments, priorities, positions and ground ETA remain available. We call this ablation \emph{explicit candidate-information support}. Supplementary Section S2 provides the field comparison and full prompt file. The analyzed cohort includes recorded errors and structured retries.''','策略：清楚列出消融移除的信息，保留后端及错误记录披露。')
m('The validation pipeline checks',r'''The validation pipeline checks action structure, identifiers, mission and aircraft status, commandability, compatibility, destination availability, priority restrictions and relevant modeled operating constraints. Candidate filtering and execution checking serve different purposes. Candidate legality describes the observed state. At execution, the checker determines whether the selected intervention can be applied to the current state.''','检查：区分观测时合法性与执行时可行性。')
m('Rejected proposals are logged',r'''The executor logs rejected proposals rather than silently converting them into a preferred action. For an accepted assignment, it updates the registry and simulator commands according to deterministic rules shared by every policy. These rules enforce modeled feasibility. Operational aviation certification lies outside this service model.''','检查：落实主体，合并重复的共同规则说明。')
m('The executor maintains the distinction',r'''The executor distinguishes proposal, issue, execution and transport completion. In the execution-delay experiment, it places accepted proposals in a pending queue. A changed command supersedes the earlier command for that task; an identical normalized command keeps the original due time. Before applying the current command, the execution pipeline revalidates it. A change in the environment can therefore affect both when a command executes and which command survives.''','执行：按队列操作说明命令的保留、替换和复核。')
m('Local aircraft contingency behavior',r'''Local aircraft contingencies run independently of supervisory decisions. Under modeled command-link loss, for example, the affected aircraft becomes unavailable for further supervisory commands and follows its local return procedure. The supervisor can select another aircraft or ground fallback for the interrupted service. Recovery therefore combines the shared local response with a replacement decision that may differ by policy.''','独立应急：将 supervisor 与 local contingency 的动作明确分开。')
m('E4A replaces this ordinary',r'''E4A replaces the ordinary observation arrangement with controlled snapshot-refresh and polling schedules. The supervisor uses the latest observed snapshot rather than an unrestricted view of the current state. E4B adds controlled waiting before execution. E4C adds inert input records around the unchanged core service problem. Each experiment changes one of these implementation conditions while retaining the respective policy definitions.''','实验方法：分清三个 E4 子实验改变什么。')

m('The three study areas',r'''The three study areas use OpenStreetMap road data from Suzhou, China (A), Amsterdam, the Netherlands (B), and Edmonton, Canada (C). OpenStreetMap provides the geographic networks. \citep{ref14} Each configured study area measures 3.2 km $\times$ 3.2 km. Figure~\ref{fig:fig02} shows the imported road networks and representative service connections. Network conversion can retain roads beyond the nominal area. The figure therefore shows the full imported networks at a common projected scale; their outlines do not represent identical nominal-area boundaries.''','场地：以 road networks 代替 substrate，拆分地图边界解释。')
m('The sites offer contrasting',r'''The sites provide contrasting operating contexts. At Site A, the meshed urban network leaves meaningful choices between continued ground service and reassignment of occupied aircraft. Site B has the highest within-boundary road density, but water barriers constrain its reference ground corridor. Site C has a higher dead-end ratio and mean sampled OD circuity, together with a longer reference service distance. These features provide different transport alternatives. Section 7 discusses why their individual causal effects cannot be separated here.''','场地：说明形态如何构成选择情境，保留因果范围限制。')
m('Every site uses a four-aircraft',r'''Every site uses a four-aircraft core fleet: two medical UAVs, one logistics UAV and one passenger eVTOL. Compatibility rules restrict which aircraft can serve each mission. Under low medical workload, the medical aircraft are idle; under high workload, they are assigned to existing services. Facilities, aircraft operations, landing sites and failures are scenario constructs. The experiments thus represent modeled services on real road networks.''','场地：明确工作负载如何改变飞机占用状态。')
m('Policies share mission semantics',r'''Within each experiment, policies share mission semantics, the action contract, candidate-generation rules and deterministic execution constraints. The prompt and B2 objective remain as specified. Across sites, geographic coordinates, road alternatives, aircraft travel distances and failure placement vary. Fault times are adapted to intercept the modeled air operation; an identical time would affect different flight phases. The cross-site evaluation therefore tests the same supervisory architecture in different network and service contexts.''','对照：写清共享项与场地变化，保留故障时间适配依据。')
# The B4a/B4b wording in the next source paragraph is ambiguous and is retained for author query Q3.
m('E4 retains Site A',r'''E4 retains Site A's core task and examines three operational changes separately. E4A varies the interval between observed snapshots, with a fault at 371 s. Scheduled polling continues throughout the observation experiment, including after some transport decisions have resolved. E4B applies the same specified delay from decision to execution to every policy, with a fault at 360 s. E4C adds unavailable, non-commandable aircraft records with zero endurance and incompatible landing capabilities. It also adds inert facility records and records of completed missions.''','实验设计：解释输入规模增加的实际内容。')
m('E4C does not add usable',r'''E4C keeps the core fleet at four aircraft and adds no usable transport capacity. Candidate invariance is checked at matched decision stages. It tests how added input affects the burden on the policy and its choices for a fixed transport decision. It does not test scheduling fifty operational aircraft or serving a proportionally larger set of urgent missions.''','实验边界：将 input burden 与扩大真实机队区分清楚。')
m('Emergency completion and deadline',r'''Emergency completion and deadline violation follow Equation (7). Existing-service damage counts non-primary missions in state INTERRUPTED, NEEDS\_REPLAN, CANCELLED or FAILED at the horizon. It describes their final service status, not physical damage or the cumulative history of interruptions. Air intervention is identified from issued actions; rejected proposals do not count.''','指标：解释 damage 的操作定义，避免读作物理损伤。')
m('Late completion incurs a fixed',r'''Late completion incurs a fixed penalty, not a charge per second late. EN\_ROUTE and ASSIGNED services incur no horizon penalty. The terminal-registry audit found that all 4,320 E3 task instances with deadlines at or before the horizon had completed. No overdue ongoing tasks were therefore omitted. A late primary CRITICAL mission contributes 240 units, and a late secondary HIGH mission contributes 135 units. SWL uses configured loss units rather than monetary welfare. We also report its CRITICAL+HIGH component for compound-level policy comparisons.''','指标：分开惩罚规则、审计事实和损失单位。')
m('The fixed scenario panel defines',r'''The estimand is defined over the fixed scenario panel. Scenario--seed runs receive equal weight, preserving E3 level sample sizes of 40, 80, 80 and 40 per policy. For each scenario, initialization restarts \nolinkurl{random.Random(seed)}, visits aircraft in sorted order and passes the same seed to SUMO. Workload can change the number of random draws, but it does not create independent scenario streams. We therefore estimate uncertainty by grouping the complete fixed panel by seed, with policies paired within each scenario and seed.''','统计方法：解释按种子分块的原因，保留估计对象和权重。')
# Keep the source's potentially ambiguous "Identical differences" statement unchanged (Q2).
m('Experiments evaluate supervisory',r'''The experiments evaluate supervisory service replacement with four core aircraft, specified fault state machines and the ground timer described in Section 4.1. External inference calls do not advance physical simulation time. E4A changes the information observed by the supervisor; E4B inserts a controlled wait before execution. Backend wall-clock latency is recorded separately. The numerical revision retains the original runs, corrects the B0 D60 duplicate-command cell through a local implementation overlay, and recalculates fixed-panel statistics. The supplementary materials provide parameters, prompts, analysis scripts and revision provenance.''','范围：分开模拟时间、推理耗时与修订披露；不移走透明性信息。')
m('Enabling air support improved',r'''Air support improved emergency transport, but the coordinated policies differed in how much incumbent service they disrupted (Figure~\ref{fig:fig03}). At A, B2 and B4b reduced deadline violations from B0's 33.33\% to 16.67\%. Their mean completion durations were 147.62 and 146.63 s, respectively. However, B4b left 0.133 damaged services per run, compared with B2's 0.058. Supplementary Table S1 provides the full site--policy summaries and intervals.''','结果 E1：先交代比较对象，再分开紧急任务速度与既有服务后果。')
m('The high-disruption, HIGH-urgency',r'''The high-disruption, HIGH-urgency, high-workload scenario at A shows what this trade-off means for service. Ground transport could meet the 300 s deadline slack, and B2 selected it in all 20 runs. B4b reassigned an occupied aircraft in 12 runs and used ground in eight. Relative to B2, completion duration decreased by 11.95 s (95\% CI -17.330 to -6.570; Holm-adjusted $p=0.002100$), while damage increased by 0.600 services per run. Both policies met every emergency deadline. Air reassignment therefore accelerated the emergency by interrupting another service, even though ground could still finish on time. An operator must weigh that interruption against the additional speed.''','结果 E1：将抽象成本取舍写成快了什么、打断了什么，保留完整推断。')
m('At B and C, large gains',r'''At B and C, coordinated policies achieved large gains over ground-only operation but produced similar outcomes to one another. Their deadline-violation rates were 0\% and 10\%, respectively, compared with B0's 50.00\% and 83.33\%. These results separate the benefit of allowing a useful transport mode from the effect of choosing a more complex supervisor.''','结果 E1：区分开放空中运输的收益和策略复杂度的作用。')
m('Explicit candidate-information support improved',r'''Explicit candidate-information support improved speed and preserved more incumbent service at A (Table 5). Relative to B4a, B4b reduced completion duration by 13.567 s, damage by 0.383 services per run and air intervention by 38.333 percentage points. Improving all three outcomes indicates more selective use of the same transport resources.''','结果消融：合并重复的方向与数值报告，保留三项端点。')
m('The information-support effect was',r'''The effect of information support differed by site. At B, no difference passed Holm adjustment; at C, all three endpoint differences were zero. Figure~\ref{fig:fig04} relates choices to ETA advantage, deadline margin and preemption. When ground is faster and avoids preemption, it is preferable on both service criteria. B1 can still select air because its rule ranks only air candidates. Available candidates therefore do not by themselves ensure a useful choice.

At A, 20 states offered faster air requiring preemption and ground that could still meet the deadline. B1, B2 and B4b selected air in 20, zero and 12 cases, respectively. The corresponding counts at B and C were 60/60/57 and 20/20/20. Thus, a conflict between speed and incumbent service did not always lead policies to choose differently.

When A had no candidate predicted to finish on time, all 40 runs per coordinated policy were late despite different mode choices. At C, 24 of 27 such cases were late. The three timely cases show that candidate ETA is approximate. These observations link explicit information support to policy decisions while distinguishing predicted deadline margins from guaranteed completion.''','结果消融：将跨站统计、策略选择和 ETA 预测边界拆成三段，每段一个信息任务。')
m('Every affected coordinated run established',r'''Every affected coordinated run established an executable replacement path in E2 (Supplementary Figure S1). Earlier assignments changed exposure to failure, so B4b had different affected counts from B1/B2; B0's conditional recovery was N/A. Despite restoration in every affected run, B4b's deadline-violation rates over all runs remained 39.06\%, 37.50\% and 62.81\% at A, B and C. Traveling along a surviving route could require more time than remained before the deadline.''','结果 E2：明确条件恢复分母与全样本迟到率，并解释剩余运输时间。')
m('B4b completed later than',r'''At A, B4b completed later than B2, and the difference passed the specified multiplicity-adjusted test (Table 6). The conditional recovery-time difference did not pass correction. Completion differences at B and C were smaller and did not pass Holm adjustment. Establishing a replacement service quickly does not eliminate the travel time remaining after a fault. Dispatch latency and deadline performance therefore describe different operational outcomes.''','结果 E2：简化审计式显著性表述，保持比较和统计结论不变。')
m('These averages contained clear limits.',r'''Coordination did not reduce loss in every setting. At A, all policies retained loss 240 in L2. At C, coordination reduced SWL only in L3, with no reduction in L1, L2 or L4. The E1 benefit of air availability therefore did not persist across every combination of failures and service demand.''','结果 E3：直接说明收益不成立的条件。')
m('B4b did not significantly reduce',r'''B4b did not significantly reduce SWL or CRITICAL+HIGH loss relative to B1 or B2 in the recorded compound comparison families. At A, its L3 and L4 SWL differences were +1.6875 (95\% CI [-1.844, 5.219]) and +3.375 ([-3.689, 10.439]), with adjusted $p=1$. The corresponding compound-level differences at B and C were zero. In these panels, surviving alternatives that could meet deadlines accounted for the transport benefit; differences between policies added little protection.''','结果 E3：保留不显著结论、区间和比较方向，使解释更直接。')
m('Primary speed alone also',r'''Mean primary completion time did not capture all service benefits. At A, coordinated policies reduced SWL even though mean primary completion took longer than under B0. The configured loss depends on which priority-weighted services miss their deadlines, not only on how quickly the primary mission finishes on average.''','结果 E3：说明为何主任务更慢仍可能降低整体损失。')
m('The sites separate coordination',r'''The sites show that an opportunity for coordination need not imply strong sensitivity to policy choice. At A, ground can remain timely while air reassignment offers a smaller speed gain at the cost of incumbent service. This site also has the strongest interface effect. B combines a dense network with a barrier-constrained reference corridor. C has more dead ends, higher sampled OD circuity and a longer reference trip. Both have large E1 coordination benefits and similar outcomes across coordinated policies.''','跨站结果：解释协调机会与策略敏感性是不同观察。')
m("C's limited E3 gains",r'''C's limited E3 gains show the boundary of this pattern: an alternative must meet the relevant deadline to avoid the configured penalty. Road geometry, facilities, air travel times and fault timing vary together across sites. Morphology helps explain the context in which the supervisor chooses; the comparison does not estimate an independent causal effect of density, circuity or redundancy.''','跨站结果：保留形态比较的非因果限定。')
m('Longer observation intervals could',r'''Longer observation intervals could leave too little time to complete the service (Figure~\ref{fig:fig07}a; Supplementary Table S4). B2/B4b completion duration increased from 140 s at OBS10 to 482 s at OBS300. Their results matched in every arm. B1 differed at OBS300, completing in 521 s. All B4b runs in OBS10--OBS60 met the deadline, with OBS60 exactly on time; all runs in OBS120/OBS300 were late.''','结果 E4A：解释 service margin 耗尽对应的完成后果。')
m('The schedule delayed both',r'''The observation schedule delayed discovery of both the task and the fault. The 300 s snapshot was taken before the task event in the same simulation second. The task first appeared at 310/330/360/360/600 s across the five arms, and the 371 s fault appeared at 380/390/420/480/600 s. OBS120 restored the affected path but completed late. OBS300 had no affected primary air chain, so conditional recovery was N/A. The snapshot timestamp alone therefore did not establish which events were visible.''','结果 E4A：按事件顺序解释同秒快照为何看不到新任务。')
m('Longer intervals also reduced',r'''Longer intervals also reduced B4b decisions from 62 to four per run. These counts cover polling over the fixed full horizon, including calls after some services had resolved. They do not estimate the call count for an adaptive policy that stops polling after completion.''','结果 E4A：明确决策调用数的统计范围。')
m('The D60 sequence changed',r'''At D60, a newer command replaced the pending intervention (Supplementary Figure S2). An air proposal selected at 300 s was due to execute at 360 s. At that time, the fault triggered a newer ground decision that superseded the air proposal. Ground fallback then waited until 420 s and completed at 602 s. The change arose from command replacement, not checker rejection of a stale action.

After the identical-command correction, B0 executes its ground command at 360 s and completes at 542 s, or 242 s after release. Its original 302 s duration included an unintended second 60 s wait. All 20 B0 D60 runs reproduce the correction. D00 and D30 controls retain 182 and 212 s, and neighboring fault times retain 242 s. Supplementary Figure S2 distinguishes the corrected ground-only sequence from B4b's genuine air-to-ground replacement. These outcomes depend on the specified event order and command semantics.''','结果 E4B：分开实际命令替换机制与代码修正记录；后者原位保留。')
m('Increasing total aircraft records',r'''Increasing total aircraft records from five to fifty raised B4b prompt tokens per logged call from 3,982.1 to 20,593.5 (Figure~\ref{fig:fig07}c; Supplementary Table S6). The active fleet remained four aircraft. Across 640 matched-stage checks, the legal candidates stayed the same. All 100 B4b runs completed on time, with no observed selection of an illegal or nonexistent resource.''','结果 E4C：将输入规模、可用候选和表现分开报告。')
m('The N05 completion mean',r'''Mean completion duration was 121.5 s in N05 and 120 s in N10--N50. N05 included one retained transport error and another decision opportunity. Across E4, the records contain four final transport-error calls and four structured retries, all retained in the analysis. These results concern input burden for a fixed service problem, not coordination of fifty operational aircraft.''','结果 E4C：保留错误与重试披露，不将关联写成未经验证的因果。')
m('We develop the Manager as',r'''The Manager treats a service intervention as the unit of transport decision-making. A joint state observation becomes useful when the candidate generator links it to a compatible resource, an executable action and an estimated completion time. The candidate interface also shows which incumbent service would be interrupted. With common checking and execution rules, researchers can compare policy preferences under the same transport contract. This extends multimodal recovery and dynamic fleet management to a failure-prone ground--air service system. \citep{ref4,ref20,ref22}''','讨论：解释架构为何有用，避免再次罗列完整方法名称。')
m('The comparison shows why',r'''A replaceable policy layer is useful because service choices matter most where feasible alternatives leave room for different preferences. Deterministic and LLM policies often produced similar outcomes when the surviving alternatives constrained what could be achieved. When ground remained timely but faster air required preemption, their choices could differ. B2 values speed and incumbent service through fixed weights; B4b sometimes interrupts an incumbent to complete the emergency faster. By exposing this choice, the Manager lets an operator assess it against service obligations.''','讨论：从比较结果提炼策略层的管理意义，不重复数值。')
m('Low-altitude capacity yields resilience',r'''Low-altitude capacity improves resilience when it provides a useful alternative that can be executed in time. E1 shows how air transport can bypass a disruption and what is lost when an occupied aircraft is reassigned. E2 distinguishes path restoration from on-time completion. E3 shows that surviving options can protect priority-weighted services, whereas exhausted alternatives leave the same loss across policies. Together, these findings link network recovery to the service outcomes that justify intervention. \citep{ref1,ref3}''','讨论：保留跨实验综合，各实验仅承担一个解释任务。')
m('The decision-log analysis identifies',r'''The decision logs help explain when choices converge or diverge. Policies tend to agree when one option is both faster and preserves incumbent service. Smaller speed gains that require preemption reveal their different preferences. Negative predicted margins identify services that are difficult to rescue, but the estimates remain approximate: a few Site C missions finished on time despite negative candidate margins. The interface must therefore show how ETA and service consequences were derived, and readers must assess timing estimates alongside realized trajectories.''','讨论：把 operating conditions 还原为具体可比较的选项。')
m('Transfer sensitivity reinforces',r'''The offline replacement analysis shows how omitted transfer time can change deadline outcomes. At Site B, timely affected services retain only 19 s of margin. Assuming a 30 s handover makes 80 previously timely services per coordinated policy late. At Site A, deterministic replacements retain 60 s, while a small number of LLM trajectories lie closer to the deadline. Path restoration remains observed in these runs, but deployment would require accounting for physical transfer time.''','讨论：明确 offline 假设改变的是迟到状态，保留路径恢复结论。')
m('Observation scheduling determines',r'''Observation scheduling determines when the supervisor can see a mission or fault. Queue rules determine whether an accepted intervention executes before circumstances change. E4 shows that sparse observation can leave too little time to meet the deadline, while execution waiting can allow a fault to replace an air command with ground service. The B0 duplicate-command correction removes a delay caused by the implementation and preserves the substantive air-to-ground replacement mechanism. A practical Manager therefore needs observations timed to service deadlines and repeat commands that do not restart a pending wait, as well as a capable selection policy.''','讨论：把抽象时间语义与 idempotent 译为具体管理要求，修正披露保留。')
m('Explicit candidate information also',r'''Explicit candidate information increases the input the policy must process. The B4a--B4b comparison measures the support provided by derived candidate facts, while E4C measures input burden around a fixed active fleet. Together, they suggest that interface design and policy selection should be considered jointly. The interface should make consequential service choices easy to compare without burying them among unnecessary records.''','讨论：说明信息支持和输入负担如何共同影响接口设计。')
m('The evidence concerns fixed,',r'''The evidence comes from fixed, site-adapted scenario panels with a four-aircraft core fleet. Road morphology varies together with facility placement, flight distance and fault timing, limiting what can be attributed to geometry alone. Ground service uses a corridor ETA timer. The registry abstracts payload custody and transfer synchronization, and the offline added-time analysis does not re-optimize the closed loop. Faults and feasibility checks follow specified service-level rules. SWL uses configured flat penalties; incumbent damage counts final states. The LLM results concern one recorded backend and prompt family, with wall-clock inference decoupled from simulated transport.

Next steps are to model task-specific ground travel and payload transfer, test transfer delays in the closed loop, expand the active fleet, and vary transport geometry under controlled conditions. These extensions would test how far the observed mechanisms generalize to other operating conditions.''','讨论边界：分开现有证据范围与下一步，全部限制保留。')
m('We propose a Ground--Low-Altitude Mobility Manager that connects',r'''The Manager connects joint transport observations to executable service reconfiguration. Its shared candidate interface lets replaceable supervisory policies compare feasibility, remaining time and consequences for incumbent services. The closed-loop experiments show when selective air support helps, when faster emergency transport costs incumbent service, and why restoring a path does not guarantee timely recovery.''','结论：用已有简称综合核心贡献与发现。')
m('Low-altitude capacity alone does not ensure resilience.',r'''Low-altitude capacity alone does not ensure resilience. It is useful when the supervisor selects a suitable cross-modal intervention and the executor applies it before the remaining service margin runs out. Surviving alternatives determine which services can be rescued. Policy preferences determine whether additional emergency speed justifies interrupting an incumbent service, and observation--execution timing determines whether the selected intervention takes effect. The Manager provides a concrete architecture and comparative evidence for managing these dependencies.''','结论：用主体和动作收束管理含义，保留适用条件。')

s('These tables report the revised',r'''The tables report service outcomes from the revised numerical analysis. Means use the original fixed scenario weights, and intervals use seed blocks. The B0 D60 results include the closed-loop duplicate-command correction. The version archive retains the original data and earlier tables.''','补充结果：先说明表格内容，随后保留分析版本和归档信息。')
s('Completion, damage and deadline-rate',r'''Completion, damage and deadline-rate intervals use 20 seed blocks, each averaging the same 12 scenarios. A zero-width interval means that this fixed-panel average did not vary across seeds; it does not establish a universal rate. Each site--policy cell contains 240 runs.''','补充结果：明确零宽区间的含义与边界。')
s('All-run denominators are',r'''All-run outcomes use 320 runs per site and policy. Recovery is conditional on the primary air chain actually being affected; it is N/A for B0. Restoration is reported as observed recovered/affected counts. We retain dependence within the fixed panel and do not apply a Wilson interval that assumes independent runs.''','补充结果：解释恢复分母及为何不用独立样本区间。')
s('The vocabulary is larger',r'''Each scenario uses only part of this vocabulary. Including an action type in the contract does not mean that the experiments validate every possible use of it. The candidate interface records legal flags and rejection reasons, and the checker applies conditions specific to each action.''','补充动作定义：简化动作支持范围的限定。')
s('The complete template is supplied',r'''The complete template is supplied as \nolinkurl{reproducibility/prompts/manager_v2.txt}, together with the input renderer and action schema. Both B4a and B4b receive the full global snapshot without its \nolinkurl{candidates} field. B4b receives that field in a separate JSON section; B4a does not. Both retain raw resource state, mission assignments, priorities, positions, deadlines, ground ETA, prompt rules and the common checker. Only B4b receives derived air ETA, completion predictions, per-candidate legality/rejection reasons and the explicit mapping to preempted missions. The ablation therefore tests explicit candidate-information support, including both derived information and its presentation.''','补充输入：按照共同输入和新增输入解释消融，保留字段路径。')
s('B2 weights and the prompt template',r'''B2 weights and the prompt template remain unchanged. The supplied YAML matrices specify mission-specific delay and cancellation penalties, secondary releases, workload assignments and site adaptations. The policy identifier names the configured backend service; the underlying model version has not been verified.''','补充参数：直接说明已知配置与未核实后端版本。')
s('The runner initializes a fresh',r'''The runner initializes a fresh \nolinkurl{random.Random(seed)} for every scenario and visits aircraft in sorted order. Each aircraft consumes an endurance draw, and each busy aircraft consumes an additional progress draw. SUMO also reuses the same seed. Workload-dependent draw counts change the realizations, but they do not create independently keyed scenario streams. We therefore retain dependence within each seed across the fixed scenario panel and pair policies by scenario and seed. This decision follows the implementation, rather than seed labels or state hashes alone.''','补充统计：按随机数调用顺序解释相关性和分块。')
s('For a complete panel, each seed',r'''For a complete panel, each seed contributes the average of its scenario-specific outcomes or paired differences. Means keep equal scenario--run weights. A t interval uses the standard deviation across 20 seed averages (10 in the E1 ablation). For a conditional endpoint with $N$ retained pairs, let $\bar d$ denote the original pair-weighted mean and $K$ the number of represented seeds. The cluster contribution is
\[
B_s=\bar d+\frac{K}{N}\sum_{i:\,s_i=s}(d_i-\bar d).
\]
The interval is $\bar d\pm t_{.975,K-1}\operatorname{sd}(B_s)/\sqrt K$. This retains the mean over jointly affected pairs without reweighting seeds that have different exposure counts. Conditional populations can differ by policy. At Site C, B4b has 201 affected runs, whereas the B4b--B2 recovery comparison includes 200 jointly affected pairs.''','补充统计：保留公式和估计对象，说明条件样本数量为何不同。')
s('Continuous tests use these seed',r'''Continuous tests use these seed contributions, with the original signed-rank fallback for constant differences. Binary tests enumerate policy-label swaps of whole seed blocks and use the total discordant paired difference as the test statistic. This preserves pairing without assuming independent pairs for McNemar inference. Scenarios, endpoints and correction families are not selected by their p-values. Intervals are unadjusted. Holm-adjusted p-values retain the original three E1 ablation, 12 E2 and 12 E3 compound endpoints per site. E1 scenario-specific and E4 single-scenario comparisons keep their original seed units.

The E2 family includes completion, recovery time, replan latency, incumbent damage, candidate reduction, deadline violation, restoration, recovered completion, ground fallback, failure-induced fallback, necessary-fallback correctness and air intervention. E3 compares B4b with B1/B2 at L2--L4 for SWL and CRITICAL+HIGH loss.''','补充统计：将推断规则与端点清单分段，保留全部比较族。')
s('All 2,880 E3 run registries',r'''All 2,880 E3 run registries were checked against their 900 s horizons. At each site, 1,440 task instances had deadlines at or before the horizon, and all were COMPLETED. Across sites, zero overdue tasks remained EN\_ROUTE or ASSIGNED. This dataset therefore requires no SWL correction or sensitivity analysis for overdue-task penalties. Background missions with 1,800 s deadlines are not classified as failures solely because they remain in service at 900 s. Incumbent damage remains a count of damaged final states.

As a complementary E1 measure, we linked recorded preemption times to the incumbent identified in the candidate log and its final interrupted state. At A, exposure from preemption to the horizon for persistently interrupted services averages 35 s per run for B2 and 80 s for B4b (B1: 300 s). This measure is truncated at the horizon; it does not capture the complete cumulative cost of interruption. Mission CSV records omit some incumbent preemption transitions, so a logged interruption duration of zero would be misleading. Initial incumbent deadlines are 1,800 s, beyond the 900 s horizon. This exposure measure therefore supports no claim about incumbent lateness.''','补充审计：分开 SWL 完整性和既有服务暴露；时长疑问保留为作者问题。')
s('The original B0 D60 action',r'''The original B0 D60 pipeline records a GROUND\_FALLBACK command at 300 s, due at 360 s. At 360 s, the fault triggers a new decision with the same normalized action and the same 181.763 s ETA field. The original queue replaces the pending command and restarts the 60 s wait. It issues the command at 420 s, and transport completes at 602 s. This extra wait produced the original 302 s completion duration.''','补充代码修正：按时间顺序解释重复命令如何造成额外等待。')
s('The revision preserves the original',r'''The revised queue keeps the original due time when a validated normalized action exactly matches a pending command. A changed action still supersedes the pending command, and the surviving command is revalidated at execution. The \nolinkurl{queue_fix.py} overlay implements this correction without changing the original project source or raw runs.

All 20 B0 D60 seeds were rerun through SUMO--BlueSky. The command issued at 360 s, and transport completed at 542 s, giving a duration of 242 s. Single-seed D00/D30 controls retain 182/212 s; fault times 359/361 s both give 242 s. B2's changed air-to-ground command retains a 302 s duration. B1 retains its air-to-air replacement sequence. Patched and unpatched control reruns both give 342 s in the current runtime, compared with the archived 341 s. This 1 s reproduction difference is unrelated to deduplication. We retain the archived cell because the correction does not change the command sequence. These regressions made no LLM calls. The original B4b traces contain genuine command replacement and remain unchanged.''','补充复现：分开队列规则、回归结果及差异披露；不删透明性信息。')
s('Table S5, main Figure 6',r'''Table S5, main Figure 6 and Supplementary Figure S2 update only the affected B0 cell. D60 tests a specified event order; it does not establish a universal transport-delay threshold. Backend wall-clock time remains separate from controlled simulation waiting.''','补充边界：简化表述；原图号待确认，不擅自修正。')
s('The model replaces a service',r'''The model replaces service assignments without tracking individual payloads. New air candidates route through the mission origin. Interrupted-service candidates route through V3 before the destination, but the supervisor can dispatch a backup before the original carrier reaches V3. Preemption interrupts and detaches the incumbent mission. Ground takeover starts a service timer based on the current reference corridor ETA. The model has no explicit states for unloading, rendezvous, loading, new inventory or re-shipment.''','补充转运：说明替代服务与实体载荷转移的模型边界。')
s('We therefore evaluate added',r'''We evaluate added transfer time through an \emph{offline trajectory-fixed sensitivity}, rather than a new closed-loop experiment. For an actually affected E2 mission with a post-failure DISPATCH, REASSIGN or GROUND\_FALLBACK, we add one hypothesized transfer delay $h$ to recorded completion. The rule is the same for every policy; uninterrupted services receive no added time. A previously timely completion becomes late when $0\le d_m-c_m<h$. Choices, fault exposure and later scheduling remain fixed. The values $h=15,30,60$ s are illustrative assumptions, not measured handling durations.''','补充敏感性：分开施加规则、判定条件及固定轨迹限制。')
s('At Site B, 80 affected',r'''At Site B, 80 affected replacements per coordinated policy are timely with 19 s remaining; adding 30 s makes all 80 late. At A, timely B1/B2 replacements have 60 s remaining, and none becomes late for $h\le60$ s. B4b has one such change at 15/30 s and two at 60 s. At C, the affected replacements in this subset are already late.

In the preemption example in Section 4.2, an extra 17 s of air-specific handling erases the realized speed advantage of 212 versus 229 s. More than 88 s also causes the emergency to miss its deadline. Adding the same handling time to both initial alternatives preserves their speed difference, so this threshold concerns an additional preemption step specifically. These checks identify conclusions that depend on omitted stages. They do not validate dynamic rescheduling with payload transfer.''','补充敏感性：分开跨站结果与抢占实例；保留严格不等式和假设范围。')
s('The original morphology routine',r'''The original morphology routine summed all imported passenger edges and divided by 10.24 km$^2$, without clipping them to its bbox argument. The revised calculation intersects each edge polyline with the configured geographic rectangle after projection through the SUMO network transform. It apportions SUMO edge lengths by the fraction of the polyline inside the rectangle and uses the same polygon's area for density. Intersection counts include only nodes inside the polygon, but count their distinct neighbors in the full graph to avoid artificial boundary intersections. Original full-network topology, OD samples and routing remain separately identified and unchanged. Site C still has higher intersection density than A; its description instead draws on dead ends, degree, circuity and facility distance.''','补充地理审计：解释每一步处理，保留原错误与修正记录。')
s('Zone applicability is evaluated',r'''The decision and execution checks evaluate whether zones apply within their configured active windows. Communication, navigation, UTM and landing-site states are not automatically repaired during these runs. Recovery means establishing a replacement service, not repairing the original aircraft or infrastructure.''','补充故障：明确检查主体与 recovery 定义。')
s('Figure 1 combines separate,',r'''Figure 1 combines separate, text-free AI-generated illustrations with editable PowerPoint text, routes, containers and markers. The map is labeled Not to scale; the finding graphics are schematic. The revision retains the authors' later PowerPoint edits removing the duplicate figure title and adjusting module labels. The authors supplied the visual reference. The illustrations depict no observations or operational deployments at the study sites. They were produced with the built-in imagegen tool and composed in PowerPoint. The records identify the tool without assigning an unverifiable model-release version.''','补充图像来源：保留 AI 生成、作者编辑和非观测图示披露。')
s('All figure text uses',r'''All figure text uses Times New Roman. Main Figure 3 uses native clustered-column charts with existing seed-block intervals. Main Figure 4 restores the candidate-geometry, preemption-choice and deadline-outcome layout. Main Figure 5 contains editable vector heatmaps and contrasts; main Figure 6 and Supplementary Figure S1 use native charts with embedded workbooks. Supplementary Figure S2 retains editable pending-command and transport segments. Both PowerPoint files keep their source slide order, with the editing guide mapping slides to current main and supplementary figure numbers.''','补充图像来源：保持精简的生产说明，图号已核实。')
s('No public repository URL is assigned.',r'''No public repository URL has been assigned. \nolinkurl{REPRODUCTION_README.md} and \nolinkurl{reproduce_analysis.ps1} specify original run locations, dependencies and executable processing order. The \nolinkurl{reproducibility/} folder contains prompts, schemas, weights, experiment configurations, derived data and a hashed file inventory. The package includes the local correction overlay, an optional regression entry point that makes no LLM calls, editable figure builders and PowerPoint sources.''','补充复现入口：以文件功能组织信息，保留所有路径和材料类别。')

m('where $G_t$ contains',r'''where $G_t$ contains ground connectivity and travel-time estimates, and $A_t$ contains aircraft states. $I_t$ describes landing infrastructure and operating restrictions; $M_t$ is the mission registry. $E_t$ records currently represented disturbances and recent events. A mission $m$ has a release time $r_m$, absolute deadline $d_m$, origin, destination, service type, priority $p_m$, state and configured penalties. An aircraft has a role, assignment status, position, remaining endurance, landing compatibility and commandability.''','符号定义：拆开状态分量的长句，各符号及含义逐一保留。')
m('where $\\mathcal O_t$ incorporates',r'''where $\mathcal O_t$ incorporates snapshot sampling and event ordering, and $\tau(t)$ is the snapshot timestamp. Snapshot age $t-\tau(t)$ helps describe visibility, but it does not identify every visible event. An event injected after a snapshot is absent even if both occur in the same simulation second. This distinction matters in the observation-scheduling experiment.''','观测定义：拆分观测年龄与事件可见性，保留同秒条件。')
m('$\\mathcal I_{m,t}$ contains',r'''$\mathcal I_{m,t}$ contains the records for mission $m$; $\mathcal C_{m,t}$ is the subset marked legal. The interface also keeps rejected resource records and their rejection reasons. Each candidate record identifies the mission, resource, transport mode and implied action. It reports estimated remaining completion duration $\widehat\eta_c$, feasibility status, endurance information, destination conditions and any incumbent service that would be displaced.''','候选定义：分开记录范围、拒绝记录和字段内容。')
m('Algorithm 1 follows the implemented',r'''Algorithm 1 processes same-time events before pending commands. Ordinary periodic decisions are suppressed while an actionable mission has a pending command; E4A uses its scheduled polling protocol instead. The identical-command rule is the queue correction evaluated in Section 6.6.2. Independent local contingencies do not wait for the queue.''','事件顺序：明确 event-before-pending 的含义，保留例外与修正指向。')

edits.sort(key=lambda e:(e['file'],original[e['file']].find(e['original'])))
for e in edits:
    offset=original[e['file']].find(e['original'])
    e['original_line']=original[e['file']][:offset].count('\n')+1
    headings=re.findall(r'\\(?:sub)*section\*?\{([^}]+)\}',original[e['file']][:offset])
    e['section']=headings[-1] if headings else 'Abstract'
for name,text in texts.items():
    (PKG/name).write_text(text,encoding='utf-8')
(OUT/'paragraph_changes.json').write_text(json.dumps(edits,ensure_ascii=False,indent=2),encoding='utf-8')

def protected(text):
    return {
      'display_equations': re.findall(r'\\begin\{equation\*?\}.*?\\end\{equation\*?\}|(?<!\\)\\\[.*?\\\]',text,re.S),
      'inline_math': re.findall(r'(?<!\\)\$[^$]*?(?<!\\)\$',text),
      'tables': re.findall(r'\\begin\{tabularx\}.*?\\end\{tabularx\}',text,re.S),
      'citations': re.findall(r'\\cite\w*\{[^}]+\}',text),
      'labels': re.findall(r'\\label\{[^}]+\}',text),
      'headings': re.findall(r'\\(?:sub)*section\*?\{[^}]+\}',text),
      'figure_files': re.findall(r'\\includegraphics.*?\{([^}]+)\}',text),
    }
from collections import Counter
checks={}
for name in texts:
    a,b=protected(original[name]),protected(texts[name])
    checks[name]={k:(Counter(a[k])==Counter(b[k]) if k=='inline_math' else a[k]==b[k]) for k in a}
    assert all(checks[name].values()),(name,checks[name])
    (OUT/(Path(name).stem+'_changes.diff')).write_text(''.join(difflib.unified_diff(original[name].splitlines(True),texts[name].splitlines(True),fromfile='original/'+name,tofile='edited/'+name)),encoding='utf-8')

def nums(text):
    # Numerical strings in prose, excluding digits embedded in policy IDs, references and command labels.
    text=re.sub(r'\\(?:ref|label|cite\w*|nolinkurl)\{[^}]*\}','',text)
    return Counter(re.findall(r'(?<![\w])\d+(?:,\d{3})*(?:\.\d+)?',text))
numdiff=[]
for e in edits:
    a,b=nums(e['original']),nums(e['edited'])
    if a!=b:
        numdiff.append({'anchor':e['anchor'],'removed':dict(a-b),'added':dict(b-a)})
checks['numeric_paragraph_differences']=numdiff
checks['original_sha256']={n:hashlib.sha256((SRC/n).read_bytes()).hexdigest() for n in ['main_revised.pdf','supplement_revised.pdf','main.tex','supplement.tex']}
(OUT/'preservation_checks.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2),encoding='utf-8')

rows=[]
for i,e in enumerate(edits,1):
    rows.append('<section><h2>'+str(i)+'. '+html.escape(e['file'])+' · '+html.escape(e['section'])+' · original line '+str(e['original_line'])+'</h2><p class="reason">'+html.escape(e['purpose'])+'</p><div class="pair"><div><h3>Original</h3><pre>'+html.escape(e['original'])+'</pre></div><div><h3>Edited</h3><pre>'+html.escape(e['edited'])+'</pre></div></div></section>')
(OUT/'paragraph_comparison.html').write_text('''<!doctype html><html lang="zh"><meta charset="utf-8"><title>段落编辑对照</title><style>body{max-width:1600px;margin:36px auto;padding:0 28px;font:16px/1.65 Georgia,"Microsoft YaHei",serif;color:#202b36;background:#f7f8fa}h1,h2,h3{font-family:Arial,"Microsoft YaHei",sans-serif}h2{font-size:18px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:24px}section{background:white;border:1px solid #dce2e8;border-radius:8px;padding:22px;margin:22px 0}pre{white-space:pre-wrap;font:inherit;overflow-wrap:anywhere}.reason{color:#315b79}h3{font-size:14px;color:#536273}@media(max-width:850px){.pair{grid-template-columns:1fr}}</style><h1>英文可读性编辑：段落对照</h1><p>左侧为原稿，右侧为编辑稿。保留 LaTeX 引用与公式标记以便准确回写；排版后的全文见 PDF。段落说明记录编辑目的。未改变章节顺序，未采纳移位建议，待确认含义保留原稿。</p>'''+''.join(rows)+'</html>',encoding='utf-8')
print(json.dumps({'output':str(OUT),'edited_paragraphs':Counter(e['file'] for e in edits),'checks':checks},ensure_ascii=False,indent=2))
